workflows:
  build-vagrant-box:
    name: Build Vagrant Box
    scripts:
      - name: Install VirtualBox (if Intel x64)
        script: |
          if [[ $(uname -m) == "x86_64" ]]; then
            brew install --cask virtualbox
          else
            wget "https://www.virtualbox.org/download/testcase/VirtualBox-7.0.97-163779-macOSArm64.dmg"
            hdiutil attach VirtualBox-7.0.97-163779-macOSArm64.dmg
            # ls /Volumes/
            sudo installer -package /Volumes/VirtualBox/VirtualBox.pkg -target /
            hdiutil detach /Volumes/VirtualBox
          fi
      - name: Install Vagrant
        script: |
          brew tap hashicorp/tap
          brew install hashicorp/tap/hashicorp-vagrant
      - name: Build Vagrant Box
        script: |
          vagrant up
          vagrant package --output box/windows-11-enterprise-evaluation-10.0.22631.Build.22631-virtual-box.box --vagrantfile Vagrantfile
