workflows:
  build-vagrant-box:
    name: Build Vagrant Box
    scripts:
      - name: Install VirtualBox (if Intel x64)
        script: |
          if [[ $(uname -m) == "x86_64" ]]; then
            brew install --cask virtualbox
          else
            wget "https://www.virtualbox.org/download/testcase/VirtualBox-7.0.97-163779-macOSArm64.dmg"
            hdiutil attach VirtualBox-7.0.97-163779-macOSArm64.dmg
            ls /Volumes/
          fi
      - name: Install Vagrant
        script: |
          brew tap hashicorp/tap
          brew install hashicorp/tap/hashicorp-vagrant
      # - vagrant up
      # - vagrant package --output my-box.box
