workflows:
  build-vagrant-box:
    name: Build Vagrant Box
    scripts:
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/hashicorp-vagrant
      - vagrant up
      # - vagrant package --output my-box.box
